---
title: "ANOVA"
description: |
  A short description of the post.
author:
  - name: Kris Sankaran
    url: {}
date: 08-03-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
library("knitr")
opts_chunk$set(cache = FALSE, message = FALSE, warning = FALSE, echo = TRUE)
```

_Readings [3.1 - 3.3](), [Rmarkdown]()_

https://uwmadison.box.com/shared/static/h3bbv7cjo0our7syhlsc0tdn5c22xyme.png
https://uwmadison.box.com/shared/static/a8jqduhcmjzj9re22a81236k3enbtzzn.png
https://uwmadison.box.com/shared/static/znpaeugwi14nxhuvz2lkmoo2ovv2jtx1.png
https://uwmadison.box.com/shared/static/n836t4q718m2o16hluvglplqi4lshgcm.png
https://uwmadison.box.com/shared/static/7prsedegwnp6wdghcw6vfv2rs7zsr7nj.png
https://uwmadison.box.com/shared/static/l40cisieegn7u37ite50eu1yeoed8v88.png

Problem Setting
ANOVA is used when you want to compare the effect of different treatments on a continuous response. For example,
How does the etch rate of a tool depend on its power setting?
How do an opera company’s different donation strategies compare with one another?
How does the average rental time compare across cars?

Visually, it can be used whenever the data can be arranged as a series of boxplots.
Model and Test Setup
Formally, consider the model



where i=1, , a and j=1, , n and the errors ijN(0, 2) are independent.

i indexes different groups
j indexes the samples within groups. 
a is the number of groups
n is the number of samples in each group 
N=na is the total number of samples

Our null hypothesis is that none of the groups deviate from the global mean. The alternative is that at least one of the groups is different. Formally,

Important Identities
The word “analysis” in ANOVA is used in the classical sense of to break something into its parts. ANOVA breaks the observed variation into distinct components,



which is abbreviated as

SStotal = SStreatments + SSerror.

If any of the groups had a mean that was different from the global mean, then you’d expect the treatment term to be larger than it would otherwise be.  How large is large enough to reject?

Since the variance within each group is 2, the variance of each yi is 2n. The blue term looks like how we would usually estimate the variances of the yi, i.e.,

On the other hand, under the null, all the yijN(,2), so we would also know,



So under the null, 


but otherwise it would be larger. 

Note that the numerator and denominator are chi-squares, with a - 1 and N - a df, respectively. It’s not obvious, but they’re also independent (this is called Cochran’s theorem). Therefore, the null reference is an F distribution with (a - 1, N - a) df.
The ANOVA Table
If we introduce MStreatments and MSE for the numerator and denominator in the ratio above, we can organize this information as,



This is also how most computer output will be displayed, so it’s worth being familiar with.
